### PR TITLE
better webpack config and multi select flow

### PR DESCRIPTION
**Pull request by existe-deja**
Based on your repo I did some modifications:

1. a better webpack config based on [vue-cli](https://github.com/vuejs/vue-cli) and [webpack-simple](https://github.com/vuejs-templates/webpack-simple) The 5 seconds reloading made me mad :)
2. some indentations, if your new to frontend it's a good practice to use a linter to correct your code. [webpack](https://github.com/vuejs-templates/webpack) template includes one if you want
3. remove the clientId props in the components (called clients in your exemple). As you can't modify a prop inside a component, your implementation was wrong

### CODE REVIEW

**Comment by Hippoom** [comment]
Really appreciate for your help, especially for the webpack improvement, I'll take some time to adopt it later. 

I pulled your request locally, it turns out the `SelectClient` still malfunctions. I'm not sure if you can reproduce it on your side. The `El Client in component` section remains empty (for display the value you selected) while the `selectClientId ` has value. This is the same if I keep `clientId` as a props by the way. See the enclosed image if I didn't make myself understood.
element-ui-questions

**Comment by existe-deja** [comment]
Here we go!

The selected value needs to be set by the event value. It seems like element-ui cast the value in the event where native vue cast an event with more options (target, etc...)

**Comment by existe-deja** [comment]
Also I noticed that you try to pass boolean as string. If you want to pass a boolean as a prop, you should bind the prop so it's interpreted, otherwise it will be a string.

Ex: 
```
<el-something
  filterable="true"/>
```

should be
```
<el-something
  v-bind:filterable="true"/>

```
or 

```
<el-something
  :filterable="true"/>
```

**Comment by existe-deja** [comment]
If you're satisfied, I'll update my answer and after that, a solved mark on it will be appreciated 😄

**Comment by Hippoom** [comment]
Sure, please do  @Lacroute 

I found out that I have to put the `clientId` from `props` to `data`，and make `dispatch` to have it updated (as you mentioned earlier that I can't update a props). 

What I don't understand is the props approach works fine for raw `<select>` , I suspect that the implementation of `<el-select>`  break something.

**Comment by existe-deja** [comment]
That's it. Hope you'll envoy Vue.

**Pull request closed without merging**
